### ISSUE TITLE
Request for information

### ISSUE THREAD

**Issue by luckyrantanplan** [JimKnowler/profile#1]
Hi Jim

Your profiling tool seems very nice, but it is hard for me to see what are the key features and the main advantages of your tool compared to yse/easy_profiler  . Could you add some info in your readme, in order to be more explicit ?

Thank you very much and have a nice day.

**Comment by JimKnowler** [comment]
Hi,

The yse/easy_profiler project looks very nice, I suspect that might be the more comprehensive profiler!

I have added a little more to the README to outline its' capabilities and to explain the Sample App if you want to quickly try this one, hopefully that can help you with your comparison.

Thanks!
